<a href="https://colab.research.google.com/github/Bleachcarte/Pytorch_with_Codemy/blob/main/Tensor_Math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSOR MATH OPERATIONS**
* Add, Subtract, Divide,Exponents...
* Shorthand and Longhand
* Reassignment

In [1]:
import torch
import numpy as np

In [11]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [13]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [14]:
#addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
#subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [16]:
#sub function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [17]:
#multiplication
tensor_a*tensor_b

tensor([ 5, 12, 21, 32])

In [18]:
#mul longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [20]:
#division / to float, // to int
tensor_b/tensor_a

tensor([5, 3, 2, 2])

In [22]:
#division longhand
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [23]:
#remainder modulus
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [24]:
#remainder longhand
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [28]:
#Exponents/ pow
tensor_b**tensor_a
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [29]:
# another way to write longhand
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
#Reassignment using underscore
tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [31]:
tensor_a

tensor([1, 2, 3, 4])

In [33]:
#tensor_a = tensor_a -tensor_b

In [35]:
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])