<a href="https://colab.research.google.com/github/Bleachcarte/Pytorch_with_Codemy/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TENSORS
* A torch.Tensor is a multi-dimensional matrix containing elements of
a single data type.

* Similar To Numpy Arrays, but full of fun things that make them work better on GPU's (vs regular CPU's).

* default data type of float32.

* More suitable for deep learning than a numpy array.

In [5]:
import torch
import numpy as np

# LISTS

In [6]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# NUMPY ARRAYS

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.02443028, 0.07685359, 0.36360624, 0.51860847],
       [0.94721262, 0.85196183, 0.91586732, 0.67859527],
       [0.21196612, 0.92530653, 0.59155865, 0.33360019]])

In [10]:
np1.dtype

dtype('float64')

#TENSORS

In [12]:
tensor_2d = torch.randn(3,4)
tensor_2d
#tensor_2d.dtype

tensor([[-0.3202, -1.8529, -0.0115,  1.0183],
        [ 2.6354, -0.6907,  0.0624,  1.4649],
        [ 0.3777,  0.4839,  1.8033, -0.3780]])

In [18]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
### reate tensor out of numpy array

my_tensor = torch.tensor(np1)
my_tensor


torch.float64